# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
markdown:            kramdown 
redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
plugins: ["jekyll-paginate"]
permalink:           pretty

# Setup
title:               PeiHsiang
tagline:             'PeiHsiang'
description:         ''
url:                 https://pshung.github.io
baseurl:             'https://pshung.github.io/'
paginate:            5

# About/contact
author:
  name:              PeiHsiang Hung
  url:               
  email:             

# Custom vars
version:             1.0.0

